[project]
name = "confmanagment"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "dynaconf[all]>=3.2.12",
    "hvac>=2.3.0",
    "pydantic>=2.12.2",
    "pydantic-settings>=2.11.0",
    "pytest>=8.4.2",
    "pyyaml>=6.0.3",
]
